[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "6vFvKHXtV5jdJDTY2AcBeyi4sXJ3LhVoydd6i2Pszz1T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/jveer634/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
